image: python:latest

cache:
  paths:
    - .cache/pip

before_script:
  - apt update -y
  - apt upgrade -y
  - python --version ; pip --version  # For debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt 

test:
  script:
    - ./software/scripts/run_pylint_on_dir.sh software/src
    - doxygen Doxyfile
  tags:
    - linux